# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Box Settings
  config.vm.box = "ubuntu/focal64"

  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.name = "serguy.box"
    # vb.memory = 512
    # vb.cpus = 1
  end

  # Network Settings
  # config.vm.network "forwarded_port", guest: 80, host: 8888
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  #config.vm.network "private_network", ip: "172.17.2.10"

end